CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    options JSONB NOT NULL,         
    correct_option INT NOT NULL,     
    category TEXT DEFAULT 'General',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    question_id BIGINT REFERENCES public.questions(id),
    selected_option INT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    completion_time_seconds INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.study_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    title TEXT NOT NULL,
    overall_score NUMERIC(5,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.plan_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT REFERENCES public.study_plans(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    due_week INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.questions (content, options, correct_option, category) VALUES
('Thẻ HTML nào dùng để tạo liên kết (hyperlink)?', '["<a>", "<link>", "<script>", "<href>"]', 0, 'Web'),
('Thuộc tính CSS nào đổi màu nền phần tử?', '["color", "background-color", "bgcolor", "canvas"]', 1, 'Web'),
('Trong JS, từ khóa nào khai báo HẰNG SỐ?', '["var", "let", "const", "static"]', 2, 'JS'),
('Hàm JS nào parse chuỗi JSON thành Object?', '["JSON.stringify()", "JSON.parse()", "JSON.toObj()", "JSON.convert()"]', 1, 'JS'),
('Mệnh đề SQL nào dùng để lấy dữ liệu?', '["FETCH", "GET", "SELECT", "PULL"]', 2, 'Database'),
('Phương thức HTTP dùng để tạo mới dữ liệu?', '["GET", "POST", "PUT", "DELETE"]', 1, 'API'),
('Mã HTTP Status Code biểu thị lỗi 404 là gì?', '["Ok", "Unauthorized", "Not Found", "Server Error"]', 2, 'API'),
('Câu lệnh Git nào tải code về máy lần đầu?', '["git fetch", "git pull", "git clone", "git commit"]', 2, 'Git'),
('JWT viết tắt của cụm từ nào?', '["Java Web Token", "JSON Web Token", "JavaScript Tool", "Joint Tech"]', 1, 'Auth'),
('Đâu KHÔNG phải là Frontend Framework?', '["React", "Vue", "Angular", "Express"]', 3, 'Web'),
('Phương thức HTTP chuẩn để cập nhật 1 phần dữ liệu?', '["PATCH", "GET", "POST", "OPTION"]', 0, 'API'),
('Thuộc tính CSS display: flex có tác dụng gì?', '["Tạo bố cục linh hoạt", "Đổi màu chữ", "Tạo hiệu ứng", "Ẩn phần tử"]', 0, 'Web'),
('RLS trong Supabase/Postgres là viết tắt của gì?', '["Row Level Security", "Real System", "Read Server", "Remote Storage"]', 0, 'Database'),
('Kết quả của typeof null trong JavaScript?', '["null", "undefined", "object", "number"]', 2, 'JS'),
('Cổng (Port) mặc định của giao thức HTTPS?', '["80", "8080", "443", "3000"]', 2, 'Network');